---
layout: null
---
/* Generated by GitHub Pages from payloads/ and _data/payloads.json. */
(function () {
    var metadata = {{ site.data.payloads | jsonify }};
    var files = [
{% assign sorted_files = site.static_files | sort: "path" %}
{% for file in sorted_files %}
{% assign directory = file.path | remove: file.name %}
{% assign extension = file.extname | downcase %}
{% if directory == "/payloads/" and extension == ".elf" %}
        {{ file.name | jsonify }},
{% endif %}
{% endfor %}
    ];
    var entries = [];
    for (var i = 0; i < files.length; i++) {
        var name = files[i];
        var details = metadata && Object.prototype.hasOwnProperty.call(metadata, name)
            ? metadata[name] : {};
        if (!details || details.hidden === true) continue;
        entries.push({
            name: name,
            title: typeof details.title === "string" && details.title
                ? details.title : name.replace(/\.elf$/i, "").replace(/[_-]+/g, " "),
            description: typeof details.description === "string" ? details.description : "",
            info: typeof details.info === "string" ? details.info : name,
            order: typeof details.order === "number" ? details.order : 1000
        });
    }
    entries.sort(function (a, b) {
        return a.order - b.order || a.title.localeCompare(b.title);
    });
    window.SLOPKIT_PAYLOADS = entries;
})();
